theme: jekyll-theme-minimal
title: Welcome to IKOMJ homepage!
description: We are currently working on this page, which will contain set of articles about basic topics in olympic mathematics. Page is created by Polish high school students, together with Polish Junior MO.

[Aktualności](ikomj.github.io)
[Skrypty](ikomj.github.io/2016_pol.pdf)
[Zadansy](ikomj.github.io)
